import React from "react";
import EventsNavbar from "../../../components/EventsNavbar";
import ChubClayOpenImage from "../../../assets/images/Chub-Cay-Open.png";
import EventInformationBg from "../../../assets/images/event-informat-bg.png";
import TournamentInfo from "../../../components/TornamentInfo";
import AwardLine from "../../../assets/images/award-dinner.svg";
import DaySchedule from "../../../components/DaySchedule";

const ChubClayOpen = () => {
  return (
    <div>
      <section className="whoo-open-hero-section">
        <img className="wahoo-bg" src={EventInformationBg} alt="fish" />
        <EventsNavbar basePath="/events" links="chubClayOpen" />
        <TournamentInfo
          title={
            <>
              Chub Cay <br></br> Open 2025
            </>
          }
          imgSrc={ChubClayOpenImage}
          altText={ChubClayOpenImage}
          date={"March 27th to March 29th, 2025"}
          description={
            <>
              The Chub Cay Open, presented by Fly Zone Fishing and hosted by
              <strong className="bold-text"> Chub Cay Marina and Resort</strong>
              , is the second tournament in a thrilling three-part fishing
              series. Scheduled to take place from{" "}
              <b style={{ fontWeight: "bold" }}>March 27 to March 29, 2025,</b>{" "}
              at the scenic{" "}
              <strong className="bold-text"> Chub Cay Marina and Resort</strong>
              in the Bahamas, this tournament promises to build on the
              excitement generated by the inaugural Chub Cay Classic. Anglers
              from around the world will converge to compete in a friendly yet
              competitive environment, showcasing their fishing skills in one of
              the most beautiful marine settings.
              <br></br>
              <br></br>The Chub Cay is set to be an exciting continuation of the
              three-tournament series, offering anglers a chance to showcase
              their skills while enjoying the breathtaking beauty of the
              Bahamas. With a commitment to competition, camaraderie, and
              conservation, this event is expected to attract both seasoned
              anglers and newcomers alike. For the latest updates and
              information, participants should check the official Fly Zone
              Fishing website as the event date approaches
            </>
          }
        />
      </section>
      <section className="schedule-section">
        <div className="container add-z-index">
          <div className="row g-4">
            <p id="chub-classic-para">
              <span>Secure your spot today</span> and make memories that will
              last a lifetime.{" "}
              <b>Let's make this Chub Cay Open a real adventure!</b>
            </p>

            <DaySchedule
              title="Schedule Of Events"
              date="March 27th to March 29th, 2025"
              events={[
                {
                  time: "4:00PM – 6:00PM",
                  text: "Registration and Bag Pick up",
                },
                { time: "6:00PM", text: "Captain’s Meeting" },
              ]}
            />

            <DaySchedule
              title="Day 1 Fishing"
              date="Friday, March 28th 2025"
              events={[
                { time: "8:00AM", text: "Call for 'Lines In'" },
                { time: "3:00PM", text: "Lines OUT" },
                {
                  time: "5:00PM",
                  text: "All boats must be back in channel marker lines",
                },
                { time: "5:30PM", text: "Scale closes" },
              ]}
            />

            <DaySchedule
              title="Day 2 Fishing"
              date="Saturday, March 29th 2025"
              events={[
                { time: "8:00AM", text: "Call for 'Lines In'" },
                { time: "3:00PM", text: "Lines OUT" },
                {
                  time: "5:00PM",
                  text: "All boats must be back in channel marker lines",
                },
                { time: "5:30PM", text: "Scale closes" },
              ]}
            />
          </div>
          <div className="text-center mt-5">
            <p className="award-text">Awards ceremony 7:00PM</p>
          </div>
        </div>
      </section>
      <div className="award-dinner container">
        <h1>Dinner</h1>
        <img src={AwardLine} alt="no-line" />
        <p className="mt-5">
          <b className="bold-text">6:00 p.m. – 9:00 p.m.</b> Complimentary
          buffet dinner for tournament entrants at{" "}
          <b className="bold-text">Clubhouse Restaurant</b>. In order to best
          accommodate everyone, a maximum of <b>6 GUESTS PER BOAT </b> are
          welcome to attend. Dinner starts at
          <b className="bold-text"> 6:00 p.m. until 9:00 p.m.</b>
        </p>
      </div>
    </div>
  );
};

export default ChubClayOpen;
