import React  , {useEffect, useState} from "react";
import { Link } from "react-router-dom";
import Correct from "../assets/correct.svg";
import Classic from "../assets/images/Chub-Cay-Classic.png";
import ChubClayOpenImage from "../assets/images/Chub-Cay-Open.png";
import ChubClayInvitationsImage from "../assets/images/Chub-Cay-Invitational.png";
import WestEndMeatfishImage from "../assets/images/West-End-Meatfish-Mania_large.png";
import BurunuBomaImage from "../assets/images/BomaMain.png";
import "../assets/css/upComingEvent.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import {
  useGetEventsCategoryForAdminMutation,
} from "../features/tournaments/api";
const events = [
  {
    title: "Chub Cay Classic",
    description:
      "The Chub Cay Classic, presented by Fly Zone Fishing, and hosted by Chub Cay Marina and Resort is the 4th annual tournament of a three-part fishing series set to take place from March 13 to March 15, 2025, at the beautiful Chub Cay Marina and Resort in the Bahamas. This highly anticipated event is designed to bring together anglers from across the globe, celebrating sport fishing while promoting camaraderie and conservation in the stunning waters surrounding Chub Cay.",
    date: "March 13th to March 15th, 2025",
    image: Classic,
    link: "/tournaments/chub-cay-classic",
    width: 400,
  },
  {
    title: "Chub Cay Open",
    description:
      "The Chub Cay Open, presented by Fly Zone Fishing and hosted by Chub Cay Marina and Resort, is the second tournament in a thrilling three-part fishing series. Scheduled to take place from March 27 to March 29, 2025, at the scenic Chub Cay Marina and Resort in the Bahamas, this tournament promises to build on the excitement generated by the inaugural Chub Cay Classic. ",
    date: "March 27th to March 29th, 2025",
    image: ChubClayOpenImage,
    link: "/tournaments/chub-cay-open",
    width: 320,
  },
  {
    title: "Chub Cay Invitational",
    description:
      "The Chub Cay Invitational, presented by Fly Zone Fishing and hosted by Chub Cay Marina and Resort, marks the third and final leg of the highly competitive three-part fishing series. The Chub Cay Invitational is Scheduled for April 11 to April 13, 2025, at the stunning Chub Cay Marina and Resort in the Bahamas, this exclusive tournament is designed specifically for members of the Chub Cay Club.",
    date: "April 11th to April 13th, 2025",
    image: ChubClayInvitationsImage,
    link: "/tournaments/chub-cay-invitational",
    width: 400,
  },
  {
    title: "Burunu Boma",
    description:
      "Brunu Boma 2025, hosted by the Visit Maldives Club, is a high-energy fishing competition set in the beautiful waters of Marina Bay, Crossroads Maldives. Taking place from May 2 to May 4, 2025, this three - day event welcomes anglers from around the world to showcase their skills and sportsmanship in a vibrant, eco-conscious setting. Designed to unite resorts and anglers in a spirit of friendly rivalry, Brunu Boma shines a light on ethical fishing, teamwork, and vibrant community experiences.",
    date: "May 2nd to May 4th, 2025",
    image: BurunuBomaImage,
    link: "/tournaments/burunu-boma",
    width: 250,
  },
  {
    title: "West End Meatfish Mania",
    description:
      "Fly Zone Fishing proudly presents the West End MeatFish Mania 2025, an electrifying fishing tournament set against the stunning backdrop of Blue Marlin Cove in West End, Grand Bahama. Taking place from May 8 to May 10, 2025, this action-packed event invites anglers from across the globe to battle it out for top prizes while targeting Tuna, Mahi-Mahi, and Wahoo in the pristine waters of the Bahamas. ",
    date: "May 8th to May 10th, 2025",
    image: WestEndMeatfishImage,
    link: "/tournaments/west-end-meatfish-mania",
    width: 370,
  },
];
// Function to extract and parse start date
const parseStartDate = (dateString) => {
  const match = dateString.match(/([A-Za-z]+) (\d+)[a-z]* to/);
  if (!match) return null;

  const [, month, day] = match;
  return new Date(`${month} ${day}, ${new Date().getFullYear()}`);
};

const EventItem = ({ event }) => (
  <div className="container d-flex flex-column mt-4 flex-xl-row gap-5 events-inner">
    <div className="hero-left ">
      <h1 className="champ-h1">{event.name}</h1>
      <p className="hero-p">{event.description}</p>
      <span className="d-flex justify-content-between">
        <ul className="list-unstyled text-start d-flex flex-column gap-4">
          <li className="d-flex align-items-center gap-2">
            <div className="checkmark-circle">
              <img src={Correct} alt="Checkmark" width={30} />
            </div>
            <strong>{event.date}</strong>
          </li>
          {[
            "blue-marlin-cove-wahoo-open",
            "blue-marlin-cove-championship",
            "chub-cay-classic-2025",
            "chub-cay-open-2025",
            "chub-cay-invitational-2025",
            "burunu-boma",
          ].includes(event.slug) ? (
            <>
              <li className="d-flex align-items-center gap-2">
                <div className="checkmark-circle">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>8:00AM - Call for 'Lines In'</strong>
              </li>
              <li className="d-flex align-items-center gap-2">
                <div className="checkmark-circle">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>3:00PM - Lines OUT</strong>
              </li>
              <li className="d-flex align-items-center gap-2">
                <div className="checkmark-circle">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>
                  5:00PM - All boats must be back in channel marker lines
                </strong>
              </li>
              <li className="d-flex align-items-center gap-2">
                <div className="checkmark-circle">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>5:30PM - Scale closes</strong>
              </li>
            </>
          ) : (
            <>
              <li className="d-flex align-items-center">
                <div className="checkmark-circle me-2">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>Registration and Bag Pick up 4:00PM–6:00PM</strong>
              </li>
              <li className="d-flex align-items-center">
                <div className="checkmark-circle me-2">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>Captain’s Meeting 6:00PM on 8th May</strong>
              </li>
              <li className="d-flex align-items-center">
                <div className="checkmark-circle me-2">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>7:00AM - Call for 'Lines In'</strong>
              </li>
              <li className="d-flex align-items-center">
                <div className="checkmark-circle me-2">
                  <img src={Correct} alt="Checkmark" width={30} />
                </div>
                <strong>4:00PM - Lines OUT</strong>
              </li>
            </>
          )}
          <li>
            <Link className="text-decoration-none text-white" to={`/tournaments/${event.slug}`} state={{ event }}>
              <button className="contact-button mt-0">More Information</button>
            </Link>
          </li>
        </ul>
        <div className="d-none d-lg-flex flex-column">
          <img
            src={event.image}
            width={event.width}
            className="upcoming-image"
          />
        </div>
      </span>
    </div>
  </div>
);

const UpcomingEvents = () => {
  const [getEvents] = useGetEventsCategoryForAdminMutation();
  const [eventData , setEventData] = useState(null)

  const fetchTournaments = async () => {
    try {
      const response = await getEvents();
      if (response?.data?.tournaments) {
        setEventData(response.data.tournaments);
      }
    } catch (err) {
      console.log("Something went wrong while fetching tournaments.");
    }
  };

  useEffect(() => {
    fetchTournaments();
  }, []);
  const today = new Date();
  // const upcomingEvents = eventData.filter((event) => {
  //   const eventStartDate = parseStartDate(event.date);
  //   return eventStartDate && eventStartDate >= today;
  // });

  return (
    <div className="mb-4 ">
      <h1 className="upcoming-event-head">
        Upcoming <span>Events</span>
      </h1>
      {eventData?.length === 0 ? (
        <p className="text-center">No upcoming events.</p>
      ) : (
        <div
          id="carouselExampleDark"
          className="carousel slide"
          data-bs-interval="false"
        >
          {/* Carousel Indicators */}
          <div className="carousel-indicators">
            {eventData?.map((_, index) => (
              <button
                key={index}
                type="button"
                data-bs-target="#carouselExampleDark"
                data-bs-slide-to={index}
                className={index === 0 ? "active" : ""}
                aria-label={`Slide ${index + 1}`}
              ></button>
            ))}
          </div>

          {/* Carousel Inner */}
          <div className="carousel-inner">
            {eventData?.map((event, index) => (
              <div
                key={index}
                className={`carousel-item ${index === 0 ? "active" : ""}`}
              >
                <EventItem event={event} />
              </div>
            ))}
          </div>

          {/* Left and Right Navigation Arrows */}
          <button
            className="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleDark"
            data-bs-slide="prev"
          >
            <span
              className="carousel-control-prev-icon"
              aria-hidden="true"
            ></span>
          </button>
          <button
            className="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleDark"
            data-bs-slide="next"
          >
            <span
              className="carousel-control-next-icon"
              aria-hidden="true"
            ></span>
          </button>
        </div>
      )}
    </div>
  );
};

export default UpcomingEvents;
